[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
challenge = "VEvkwFjBdmAEhfvQdB8qxnwnmfz5ygUkjyZCZgiEhKc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
